### ISSUE TITLE
crypto@1.0.1

### ISSUE THREAD

**Issue by majinmartin93** [scottie/graviex-dumper#1]
npm WARN deprecated crypto@1.0.1: This package is no longer supported. It's now a built-in Node module. If you've depended on crypto, you should switch to the one that's built-in.

**Comment by majinmartin93** [comment]
/usr/local/lib/node_modules/graviex-dumper/node_modules/gradient-string/index.js:8
function InitGradient(...args) {
                      ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/graviex-dumper/node_modules/chalk-animation/index.js:4:18)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
